//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AeropuertoUned.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVIONES
    {
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Serie { get; set; }
        public string Nombre_Avion { get; set; }
        public string Dimensiones { get; set; }
        public string Recorrido { get; set; }
        public string Numero_Orden { get; set; }
        public string Tecnico { get; set; }
    }
}
